/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rvrjc.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rvrjc.portal.model.Invoice;
import com.rvrjc.portal.service.InvoiceLocalServiceUtil;

/**
 * The extended model base implementation for the Invoice service. Represents a row in the &quot;rvrjc_Invoice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InvoiceImpl}.
 * </p>
 *
 * @author suresh
 * @see InvoiceImpl
 * @see com.rvrjc.portal.model.Invoice
 * @generated
 */
public abstract class InvoiceBaseImpl extends InvoiceModelImpl
	implements Invoice {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a invoice model instance should use the {@link Invoice} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			InvoiceLocalServiceUtil.addInvoice(this);
		}
		else {
			InvoiceLocalServiceUtil.updateInvoice(this);
		}
	}
}