/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rvrjc.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Address service. Represents a row in the &quot;rvrjc_Address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rvrjc.portal.model.impl.AddressModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rvrjc.portal.model.impl.AddressImpl}.
 * </p>
 *
 * @author suresh
 * @see Address
 * @see com.rvrjc.portal.model.impl.AddressImpl
 * @see com.rvrjc.portal.model.impl.AddressModelImpl
 * @generated
 */
public interface AddressModel extends BaseModel<Address> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a address model instance should use the {@link Address} interface instead.
	 */

	/**
	 * Returns the primary key of this address.
	 *
	 * @return the primary key of this address
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this address.
	 *
	 * @param primaryKey the primary key of this address
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the address ID of this address.
	 *
	 * @return the address ID of this address
	 */
	public long getAddressId();

	/**
	 * Sets the address ID of this address.
	 *
	 * @param addressId the address ID of this address
	 */
	public void setAddressId(long addressId);

	/**
	 * Returns the door no of this address.
	 *
	 * @return the door no of this address
	 */
	@AutoEscape
	public String getDoorNo();

	/**
	 * Sets the door no of this address.
	 *
	 * @param doorNo the door no of this address
	 */
	public void setDoorNo(String doorNo);

	/**
	 * Returns the city of this address.
	 *
	 * @return the city of this address
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this address.
	 *
	 * @param city the city of this address
	 */
	public void setCity(String city);

	/**
	 * Returns the mandal of this address.
	 *
	 * @return the mandal of this address
	 */
	@AutoEscape
	public String getMandal();

	/**
	 * Sets the mandal of this address.
	 *
	 * @param mandal the mandal of this address
	 */
	public void setMandal(String mandal);

	/**
	 * Returns the district of this address.
	 *
	 * @return the district of this address
	 */
	@AutoEscape
	public String getDistrict();

	/**
	 * Sets the district of this address.
	 *
	 * @param district the district of this address
	 */
	public void setDistrict(String district);

	/**
	 * Returns the state of this address.
	 *
	 * @return the state of this address
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this address.
	 *
	 * @param state the state of this address
	 */
	public void setState(String state);

	/**
	 * Returns the add country of this address.
	 *
	 * @return the add country of this address
	 */
	@AutoEscape
	public String getAddCountry();

	/**
	 * Sets the add country of this address.
	 *
	 * @param addCountry the add country of this address
	 */
	public void setAddCountry(String addCountry);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rvrjc.portal.model.Address address);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rvrjc.portal.model.Address> toCacheModel();

	@Override
	public com.rvrjc.portal.model.Address toEscapedModel();

	@Override
	public com.rvrjc.portal.model.Address toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}