/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rvrjc.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Course service. Represents a row in the &quot;rvrjc_Course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rvrjc.portal.model.impl.CourseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rvrjc.portal.model.impl.CourseImpl}.
 * </p>
 *
 * @author suresh
 * @see Course
 * @see com.rvrjc.portal.model.impl.CourseImpl
 * @see com.rvrjc.portal.model.impl.CourseModelImpl
 * @generated
 */
public interface CourseModel extends BaseModel<Course> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course model instance should use the {@link Course} interface instead.
	 */

	/**
	 * Returns the primary key of this course.
	 *
	 * @return the primary key of this course
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course.
	 *
	 * @param primaryKey the primary key of this course
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cno of this course.
	 *
	 * @return the cno of this course
	 */
	public long getCno();

	/**
	 * Sets the cno of this course.
	 *
	 * @param cno the cno of this course
	 */
	public void setCno(long cno);

	/**
	 * Returns the ccode of this course.
	 *
	 * @return the ccode of this course
	 */
	@AutoEscape
	public String getCcode();

	/**
	 * Sets the ccode of this course.
	 *
	 * @param ccode the ccode of this course
	 */
	public void setCcode(String ccode);

	/**
	 * Returns the cname of this course.
	 *
	 * @return the cname of this course
	 */
	@AutoEscape
	public String getCname();

	/**
	 * Sets the cname of this course.
	 *
	 * @param cname the cname of this course
	 */
	public void setCname(String cname);

	/**
	 * Returns the cfee of this course.
	 *
	 * @return the cfee of this course
	 */
	public int getCfee();

	/**
	 * Sets the cfee of this course.
	 *
	 * @param cfee the cfee of this course
	 */
	public void setCfee(int cfee);

	/**
	 * Returns the cdescription of this course.
	 *
	 * @return the cdescription of this course
	 */
	@AutoEscape
	public String getCdescription();

	/**
	 * Sets the cdescription of this course.
	 *
	 * @param cdescription the cdescription of this course
	 */
	public void setCdescription(String cdescription);

	/**
	 * Returns the created on of this course.
	 *
	 * @return the created on of this course
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this course.
	 *
	 * @param createdOn the created on of this course
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this course.
	 *
	 * @return the created by of this course
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this course.
	 *
	 * @param createdBy the created by of this course
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified on of this course.
	 *
	 * @return the modified on of this course
	 */
	public Date getModifiedOn();

	/**
	 * Sets the modified on of this course.
	 *
	 * @param modifiedOn the modified on of this course
	 */
	public void setModifiedOn(Date modifiedOn);

	/**
	 * Returns the modified by of this course.
	 *
	 * @return the modified by of this course
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this course.
	 *
	 * @param modifiedBy the modified by of this course
	 */
	public void setModifiedBy(String modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rvrjc.portal.model.Course course);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rvrjc.portal.model.Course> toCacheModel();

	@Override
	public com.rvrjc.portal.model.Course toEscapedModel();

	@Override
	public com.rvrjc.portal.model.Course toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}