/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rvrjc.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Department service. Represents a row in the &quot;rvrjc_Department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rvrjc.portal.model.impl.DepartmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rvrjc.portal.model.impl.DepartmentImpl}.
 * </p>
 *
 * @author suresh
 * @see Department
 * @see com.rvrjc.portal.model.impl.DepartmentImpl
 * @see com.rvrjc.portal.model.impl.DepartmentModelImpl
 * @generated
 */
public interface DepartmentModel extends BaseModel<Department> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a department model instance should use the {@link Department} interface instead.
	 */

	/**
	 * Returns the primary key of this department.
	 *
	 * @return the primary key of this department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this department.
	 *
	 * @param primaryKey the primary key of this department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dno of this department.
	 *
	 * @return the dno of this department
	 */
	public long getDno();

	/**
	 * Sets the dno of this department.
	 *
	 * @param dno the dno of this department
	 */
	public void setDno(long dno);

	/**
	 * Returns the dname of this department.
	 *
	 * @return the dname of this department
	 */
	@AutoEscape
	public String getDname();

	/**
	 * Sets the dname of this department.
	 *
	 * @param dname the dname of this department
	 */
	public void setDname(String dname);

	/**
	 * Returns the created on of this department.
	 *
	 * @return the created on of this department
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this department.
	 *
	 * @param createdOn the created on of this department
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this department.
	 *
	 * @return the created by of this department
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this department.
	 *
	 * @param createdBy the created by of this department
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified on of this department.
	 *
	 * @return the modified on of this department
	 */
	public Date getModifiedOn();

	/**
	 * Sets the modified on of this department.
	 *
	 * @param modifiedOn the modified on of this department
	 */
	public void setModifiedOn(Date modifiedOn);

	/**
	 * Returns the modified by of this department.
	 *
	 * @return the modified by of this department
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this department.
	 *
	 * @param modifiedBy the modified by of this department
	 */
	public void setModifiedBy(String modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rvrjc.portal.model.Department department);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rvrjc.portal.model.Department> toCacheModel();

	@Override
	public com.rvrjc.portal.model.Department toEscapedModel();

	@Override
	public com.rvrjc.portal.model.Department toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}