/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rvrjc.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Student service. Represents a row in the &quot;rvrjc_Student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rvrjc.portal.model.impl.StudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rvrjc.portal.model.impl.StudentImpl}.
 * </p>
 *
 * @author suresh
 * @see Student
 * @see com.rvrjc.portal.model.impl.StudentImpl
 * @see com.rvrjc.portal.model.impl.StudentModelImpl
 * @generated
 */
public interface StudentModel extends BaseModel<Student> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student model instance should use the {@link Student} interface instead.
	 */

	/**
	 * Returns the primary key of this student.
	 *
	 * @return the primary key of this student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student.
	 *
	 * @param primaryKey the primary key of this student
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sno of this student.
	 *
	 * @return the sno of this student
	 */
	public long getSno();

	/**
	 * Sets the sno of this student.
	 *
	 * @param sno the sno of this student
	 */
	public void setSno(long sno);

	/**
	 * Returns the first name of this student.
	 *
	 * @return the first name of this student
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this student.
	 *
	 * @param firstName the first name of this student
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the middle name of this student.
	 *
	 * @return the middle name of this student
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this student.
	 *
	 * @param middleName the middle name of this student
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the last name of this student.
	 *
	 * @return the last name of this student
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this student.
	 *
	 * @param lastName the last name of this student
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the gender of this student.
	 *
	 * @return the gender of this student
	 */
	public int getGender();

	/**
	 * Sets the gender of this student.
	 *
	 * @param gender the gender of this student
	 */
	public void setGender(int gender);

	/**
	 * Returns the date of birth of this student.
	 *
	 * @return the date of birth of this student
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this student.
	 *
	 * @param dateOfBirth the date of birth of this student
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the email of this student.
	 *
	 * @return the email of this student
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this student.
	 *
	 * @param email the email of this student
	 */
	public void setEmail(String email);

	/**
	 * Returns the emcet rank of this student.
	 *
	 * @return the emcet rank of this student
	 */
	public long getEmcetRank();

	/**
	 * Sets the emcet rank of this student.
	 *
	 * @param emcetRank the emcet rank of this student
	 */
	public void setEmcetRank(long emcetRank);

	/**
	 * Returns the dno of this student.
	 *
	 * @return the dno of this student
	 */
	public long getDno();

	/**
	 * Sets the dno of this student.
	 *
	 * @param dno the dno of this student
	 */
	public void setDno(long dno);

	/**
	 * Returns the address ID of this student.
	 *
	 * @return the address ID of this student
	 */
	public long getAddressId();

	/**
	 * Sets the address ID of this student.
	 *
	 * @param addressId the address ID of this student
	 */
	public void setAddressId(long addressId);

	/**
	 * Returns the liferay user ID of this student.
	 *
	 * @return the liferay user ID of this student
	 */
	public long getLiferayUserId();

	/**
	 * Sets the liferay user ID of this student.
	 *
	 * @param liferayUserId the liferay user ID of this student
	 */
	public void setLiferayUserId(long liferayUserId);

	/**
	 * Returns the liferay user uuid of this student.
	 *
	 * @return the liferay user uuid of this student
	 * @throws SystemException if a system exception occurred
	 */
	public String getLiferayUserUuid() throws SystemException;

	/**
	 * Sets the liferay user uuid of this student.
	 *
	 * @param liferayUserUuid the liferay user uuid of this student
	 */
	public void setLiferayUserUuid(String liferayUserUuid);

	/**
	 * Returns the created on of this student.
	 *
	 * @return the created on of this student
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this student.
	 *
	 * @param createdOn the created on of this student
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this student.
	 *
	 * @return the created by of this student
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this student.
	 *
	 * @param createdBy the created by of this student
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified on of this student.
	 *
	 * @return the modified on of this student
	 */
	public Date getModifiedOn();

	/**
	 * Sets the modified on of this student.
	 *
	 * @param modifiedOn the modified on of this student
	 */
	public void setModifiedOn(Date modifiedOn);

	/**
	 * Returns the modified by of this student.
	 *
	 * @return the modified by of this student
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this student.
	 *
	 * @param modifiedBy the modified by of this student
	 */
	public void setModifiedBy(String modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rvrjc.portal.model.Student student);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rvrjc.portal.model.Student> toCacheModel();

	@Override
	public com.rvrjc.portal.model.Student toEscapedModel();

	@Override
	public com.rvrjc.portal.model.Student toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}