/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rvrjc.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Teacher service. Represents a row in the &quot;rvrjc_Teacher&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rvrjc.portal.model.impl.TeacherModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rvrjc.portal.model.impl.TeacherImpl}.
 * </p>
 *
 * @author suresh
 * @see Teacher
 * @see com.rvrjc.portal.model.impl.TeacherImpl
 * @see com.rvrjc.portal.model.impl.TeacherModelImpl
 * @generated
 */
public interface TeacherModel extends BaseModel<Teacher> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a teacher model instance should use the {@link Teacher} interface instead.
	 */

	/**
	 * Returns the primary key of this teacher.
	 *
	 * @return the primary key of this teacher
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this teacher.
	 *
	 * @param primaryKey the primary key of this teacher
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tid of this teacher.
	 *
	 * @return the tid of this teacher
	 */
	public long getTid();

	/**
	 * Sets the tid of this teacher.
	 *
	 * @param tid the tid of this teacher
	 */
	public void setTid(long tid);

	/**
	 * Returns the first name of this teacher.
	 *
	 * @return the first name of this teacher
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this teacher.
	 *
	 * @param firstName the first name of this teacher
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the middle name of this teacher.
	 *
	 * @return the middle name of this teacher
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this teacher.
	 *
	 * @param middleName the middle name of this teacher
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the last name of this teacher.
	 *
	 * @return the last name of this teacher
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this teacher.
	 *
	 * @param lastName the last name of this teacher
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the gender of this teacher.
	 *
	 * @return the gender of this teacher
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this teacher.
	 *
	 * @param gender the gender of this teacher
	 */
	public void setGender(String gender);

	/**
	 * Returns the email of this teacher.
	 *
	 * @return the email of this teacher
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this teacher.
	 *
	 * @param email the email of this teacher
	 */
	public void setEmail(String email);

	/**
	 * Returns the phno of this teacher.
	 *
	 * @return the phno of this teacher
	 */
	public long getPhno();

	/**
	 * Sets the phno of this teacher.
	 *
	 * @param phno the phno of this teacher
	 */
	public void setPhno(long phno);

	/**
	 * Returns the liferay user ID of this teacher.
	 *
	 * @return the liferay user ID of this teacher
	 */
	public long getLiferayUserId();

	/**
	 * Sets the liferay user ID of this teacher.
	 *
	 * @param liferayUserId the liferay user ID of this teacher
	 */
	public void setLiferayUserId(long liferayUserId);

	/**
	 * Returns the liferay user uuid of this teacher.
	 *
	 * @return the liferay user uuid of this teacher
	 * @throws SystemException if a system exception occurred
	 */
	public String getLiferayUserUuid() throws SystemException;

	/**
	 * Sets the liferay user uuid of this teacher.
	 *
	 * @param liferayUserUuid the liferay user uuid of this teacher
	 */
	public void setLiferayUserUuid(String liferayUserUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rvrjc.portal.model.Teacher teacher);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rvrjc.portal.model.Teacher> toCacheModel();

	@Override
	public com.rvrjc.portal.model.Teacher toEscapedModel();

	@Override
	public com.rvrjc.portal.model.Teacher toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}